# service-mesh：
"istio/pilot:1.6.10": "registry.cn-beijing.aliyuncs.com/kubesphereio/pilot"
"istio/proxyv2:1.6.10": "registry.cn-beijing.aliyuncs.com/kubesphereio/proxyv2"
"kubesphere/kiali-operator": "registry.cn-beijing.aliyuncs.com/kubesphereio/kiali-operator"
"kubesphere/kiali": "registry.cn-beijing.aliyuncs.com/kubesphereio/kiali"
"jaegertracing/jaeger-agent:1.17": "registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-agent"
"jaegertracing/jaeger-collector:1.17": "registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-collector"
"jaegertracing/jaeger-operator:1.17.1": "registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-operator"
"jaegertracing/jaeger-query:1.17": "registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-query"
"jaegertracing/jaeger-es-index-cleaner:1.17": "registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-es-index-cleaner"
"kubesphere/examples-bookinfo-productpage-v1": "registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-productpage-v1"
"kubesphere/examples-bookinfo-reviews-v1": "registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-reviews-v1"
"kubesphere/examples-bookinfo-reviews-v2": "registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-reviews-v2"
"kubesphere/examples-bookinfo-reviews-v3": "registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-reviews-v3"
"kubesphere/examples-bookinfo-details-v1": "registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-details-v1"
"kubesphere/examples-bookinfo-ratings-v1": "registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-ratings-v1"

# microservice samples
"gcr.io/google-samples/microservices-demo/adservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/adservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/cartservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/cartservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/checkoutservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/currencyservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/currencyservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/emailservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/emailservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/frontend:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/frontend:v0.2.3"
"gcr.io/google-samples/microservices-demo/paymentservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/paymentservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/productcatalogservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/recommendationservice:v0.2.3"
"redis:alpine": "registry.cn-beijing.aliyuncs.com/kubesphereio/redis:alpine"
"gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/shippingservice:v0.2.3"
"gcr.io/google-samples/microservices-demo/loadgenerator:v0.2.3": "registry.cn-beijing.aliyuncs.com/kubesphereio/loadgenerator:v0.2.3"

# multicluster:
"kubesphere/kubefed": "registry.cn-beijing.aliyuncs.com/kubesphereio/kubefed"
"kubesphere/tower": "registry.cn-beijing.aliyuncs.com/kubesphereio/tower"

# weave scope
"weaveworks/scope:1.13.0": "registry.cn-beijing.aliyuncs.com/kubesphereio/scope"

